<!DOCTYPE html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Administración - Plaza Local</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="min-h-screen bg-[#FAF8F4] text-[#17313A] antialiased"><header class="border-b border-[#123B4A]/10 bg-white"><div class="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a class="font-black" href="{{ route('dashboard') }}">Plaza Local</a><div class="flex gap-2"><a class="rounded-full border px-4 py-2 text-sm font-black" href="{{ route('disputes.admin-index') }}">Disputas</a><a class="rounded-full border px-4 py-2 text-sm font-black" href="{{ route('dashboard') }}">Inicio</a></div></div></header>
<main class="mx-auto max-w-7xl px-5 py-9">@if(session('status'))<div class="mb-6 rounded-2xl bg-[#E9F7F0] px-5 py-4 text-sm font-black text-[#14734A]">{{ session('status') }}</div>@endif @if($errors->any())<div class="mb-6 rounded-2xl bg-red-50 px-5 py-4 text-sm font-black text-red-700">{{ $errors->first() }}</div>@endif
<p class="text-xs font-black uppercase tracking-[.18em] text-[#F97316]">Operación</p><h1 class="mt-2 text-3xl font-black">Panel administrativo</h1>
<section class="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['Usuarios'=>$metrics['users'],'Proveedores pendientes'=>$metrics['pending_vendors'],'Disputas abiertas'=>$metrics['open_disputes'],'Órdenes activas'=>$metrics['active_orders']] as $label=>$value)<div class="rounded-3xl border border-[#123B4A]/10 bg-white p-5"><strong class="text-3xl">{{ $value }}</strong><p class="mt-2 text-sm font-bold text-[#6B7D83]">{{ $label }}</p></div>@endforeach</section>
<div class="mt-8 grid gap-6 xl:grid-cols-2"><section class="rounded-[1.75rem] border border-[#123B4A]/10 bg-white p-6"><h2 class="text-xl font-black">Proveedores</h2><div class="mt-5 space-y-4">@foreach($vendors as $vendor)<article class="rounded-2xl bg-[#FAF8F4] p-4"><div class="flex flex-wrap justify-between gap-3"><div><strong>{{ $vendor->display_name }}</strong><p class="text-xs font-bold text-[#6B7D83]">{{ $vendor->user->email }} · {{ $vendor->status }}</p></div><div class="flex gap-2">@if($vendor->status !== 'active')<form method="POST" action="{{ route('admin.vendors.approve', $vendor) }}">@csrf @method('PATCH')<button class="rounded-full bg-[#14734A] px-4 py-2 text-xs font-black text-white">Aprobar</button></form>@endif</div></div>@if($vendor->status === 'active')<form class="mt-3 flex gap-2" method="POST" action="{{ route('admin.vendors.suspend', $vendor) }}">@csrf @method('PATCH')<input class="min-w-0 flex-1 rounded-xl border px-3 py-2 text-xs" name="reason" minlength="10" required placeholder="Motivo de suspensión"><button class="rounded-full border border-red-200 px-4 py-2 text-xs font-black text-red-700">Suspender</button></form>@endif</article>@endforeach</div></section>
<section class="rounded-[1.75rem] border border-[#123B4A]/10 bg-white p-6"><h2 class="text-xl font-black">Usuarios y autoridad</h2><div class="mt-5 space-y-3">@foreach($users as $user)<article class="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-[#FAF8F4] p-4"><div><strong>{{ $user->name }}</strong><p class="text-xs font-bold text-[#6B7D83]">{{ $user->email }} · {{ $user->roles->pluck('name')->join(', ') }}</p></div>@if($isSuperadmin && !$user->hasRole('superadmin'))<div>@if($user->hasRole('admin'))<form method="POST" action="{{ route('admin.users.revoke', $user) }}">@csrf @method('DELETE')<button class="rounded-full border border-red-200 px-4 py-2 text-xs font-black text-red-700">Retirar admin</button></form>@else<form method="POST" action="{{ route('admin.users.grant', $user) }}">@csrf<button class="rounded-full bg-[#123B4A] px-4 py-2 text-xs font-black text-white">Hacer admin</button></form>@endif</div>@endif</article>@endforeach</div></section></div>
@if($isSuperadmin)
<section class="mt-6 rounded-[1.75rem] border border-[#123B4A]/10 bg-white p-6">
<h2 class="text-xl font-black">Capacidades comerciales</h2><p class="mt-2 text-sm font-semibold text-[#6B7D83]">Cliente y proveedor pueden coexistir. Los permisos administrativos no activan ninguna de estas capacidades automáticamente.</p>
<div class="mt-5 grid gap-3 md:grid-cols-2">@foreach($users as $user)
<article class="rounded-2xl bg-[#FAF8F4] p-4"><strong>{{ $user->name }}</strong><p class="mt-1 text-xs font-bold text-[#6B7D83]">{{ $user->email }}</p>
<div class="mt-4 flex flex-wrap gap-2">@foreach(['client'=>'Cliente','provider'=>'Proveedor'] as $capability=>$label)
@if($user->hasRole($capability))
<form method="POST" action="{{ route('admin.users.capabilities.revoke', [$user, $capability]) }}">@csrf @method('DELETE')<button class="rounded-full border border-red-200 px-3 py-2 text-xs font-black text-red-700" title="Los datos históricos se conservan">Retirar {{ $label }}</button></form>
@else
<form method="POST" action="{{ route('admin.users.capabilities.grant', [$user, $capability]) }}">@csrf<button class="rounded-full bg-[#123B4A] px-3 py-2 text-xs font-black text-white">Agregar {{ $label }}</button></form>
@endif
@endforeach</div></article>
@endforeach</div>
</section>
@endif
<section class="mt-6 rounded-[1.75rem] border border-[#123B4A]/10 bg-white p-6"><h2 class="text-xl font-black">Auditoría reciente</h2><div class="mt-4 overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><thead><tr class="text-[#6B7D83]"><th class="p-3">Fecha</th><th class="p-3">Administrador</th><th class="p-3">Acción</th><th class="p-3">Objetivo</th></tr></thead><tbody>@foreach($auditLogs as $log)<tr class="border-t border-[#123B4A]/10"><td class="p-3">{{ $log->created_at->format('d/m/Y H:i') }}</td><td class="p-3">{{ $log->user?->name ?? 'Sistema' }}</td><td class="p-3 font-black">{{ $log->action }}</td><td class="p-3">{{ class_basename($log->subject_type) }} #{{ $log->subject_id }}</td></tr>@endforeach</tbody></table></div></section></main></body></html>
