<?php

use App\Http\Controllers\AdminAccountController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdminDirectoryController;
use App\Http\Controllers\AdminInsightsController;
use App\Http\Controllers\AdminTeamController;
use App\Http\Controllers\Auth\AdminPasswordController;
use App\Http\Controllers\Auth\AdminSessionController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\EmailVerificationNotificationController;
use App\Http\Controllers\Auth\PhoneVerificationController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\ConversationController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DisputeController;
use App\Http\Controllers\ExploreController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobProposalController;
use App\Http\Controllers\JobVacancyController;
use App\Http\Controllers\MarketplaceCapabilityController;
use App\Http\Controllers\MercadoPagoWebhookController;
use App\Http\Controllers\MoreController;
use App\Http\Controllers\NegotiationConversationController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PostalCodeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\PostEngagementController;
use App\Http\Controllers\PostManagementController;
use App\Http\Controllers\PostPromotionController;
use App\Http\Controllers\ProductOrderController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProfileFollowController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\ServiceOrderController;
use App\Http\Controllers\StripeConnectController;
use App\Http\Controllers\StripeWebhookController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\VendorVerificationDocumentController;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');
Route::get('/explorar', ExploreController::class)->name('explore');
Route::get('/codigos-postales/{postalCode}', [PostalCodeController::class, 'show'])->whereNumber('postalCode')->middleware('throttle:60,1')->name('postal-codes.show');
Route::get('/perfiles/{user}', [ProfileController::class, 'show'])->name('profile.show');
Route::get('/empleo', [JobVacancyController::class, 'index'])->name('vacancies.index');
Route::get('/empleo/{vacancy}', [JobVacancyController::class, 'show'])->name('vacancies.show');
Route::post('/webhooks/stripe', StripeWebhookController::class)->name('stripe.webhook');
Route::post('/webhooks/mercado-pago', MercadoPagoWebhookController::class)->name('mercadopago.webhook');

Route::middleware('guest')->group(function () {
    Route::get('/register', [RegisteredUserController::class, 'create'])->name('register');
    Route::post('/register', [RegisteredUserController::class, 'store']);
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
});

Route::middleware(['auth:web', 'marketplace.identity', 'account.active'])->group(function () {
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
    Route::post('/mi-cuenta/modo/{mode}', [MarketplaceCapabilityController::class, 'switchMode'])->name('capabilities.switch');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/mas', MoreController::class)->name('more.index');
    Route::get('/mi-perfil/editar', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/mi-perfil', [ProfileController::class, 'update'])->name('profile.update');
    Route::put('/mi-perfil/intereses', [ProfileController::class, 'updateInterests'])->name('profile.interests.update');
    Route::post('/perfiles/{user}/seguir', [ProfileFollowController::class, 'toggle'])->name('profiles.follow.toggle');
    Route::get('/soporte', [SupportController::class, 'index'])->name('support.index');
    Route::get('/soporte/nueva', [SupportController::class, 'create'])->name('support.create');
    Route::post('/soporte', [SupportController::class, 'store'])->name('support.store');
    Route::get('/soporte/{ticket}', [SupportController::class, 'show'])->name('support.show');
    Route::get('/soporte/{ticket}/mensajes', [SupportController::class, 'messages'])->name('support.messages.index');
    Route::post('/soporte/{ticket}/respuestas', [SupportController::class, 'reply'])->name('support.reply');
    Route::get('/actividad/resumen', [NotificationController::class, 'summary'])->middleware('throttle:120,1')->name('activity.summary');
    Route::post('/publicaciones', [PostController::class, 'store'])->name('posts.store');
    Route::middleware('verified')->group(function () {
        Route::post('/mi-cuenta/capacidades/{capability}', [MarketplaceCapabilityController::class, 'activate'])->name('capabilities.activate');
        Route::get('/mi-empleo', [JobVacancyController::class, 'mine'])->name('vacancies.mine');
        Route::get('/empleo-publicar', [JobVacancyController::class, 'create'])->name('vacancies.create');
        Route::post('/empleo', [JobVacancyController::class, 'store'])->name('vacancies.store');
        Route::post('/empleo/{vacancy}/pagar', [JobVacancyController::class, 'pay'])->name('vacancies.pay');
        Route::post('/empleo/{vacancy}/postular', [JobVacancyController::class, 'apply'])->name('vacancies.apply');
        Route::patch('/empleo/{vacancy}/cerrar', [JobVacancyController::class, 'close'])->name('vacancies.close');
        Route::post('/mi-perfil/solicitar-verificacion', [MarketplaceCapabilityController::class, 'submitProviderApplication'])->name('provider-applications.submit');
        Route::post('/mi-perfil/documentos-verificacion', [VendorVerificationDocumentController::class, 'store'])->middleware('throttle:6,1')->name('verification-documents.store');
        Route::get('/documentos-verificacion/{document}', [VendorVerificationDocumentController::class, 'download'])->name('verification-documents.download');
        Route::post('/stripe/conectar', [StripeConnectController::class, 'onboard'])->name('stripe.connect');
        Route::get('/stripe/conectar/actualizar', [StripeConnectController::class, 'refresh'])->name('stripe.connect.refresh');
        Route::get('/stripe/conectar/resultado', [StripeConnectController::class, 'returned'])->name('stripe.connect.return');
        Route::get('/publicaciones/{post}/editar', [PostManagementController::class, 'edit'])->name('posts.edit');
        Route::put('/publicaciones/{post}', [PostManagementController::class, 'update'])->name('posts.update');
        Route::post('/publicaciones/{post}/reaccion', [PostEngagementController::class, 'toggleReaction'])->name('posts.reactions.toggle');
        Route::get('/publicaciones/{post}/comentarios', [PostEngagementController::class, 'comments'])->name('posts.comments.index');
        Route::post('/publicaciones/{post}/comentarios', [PostEngagementController::class, 'comment'])->name('posts.comments.store');
        Route::patch('/comentarios/{comment}', [PostEngagementController::class, 'updateComment'])->name('posts.comments.update');
        Route::delete('/comentarios/{comment}', [PostEngagementController::class, 'deleteComment'])->name('posts.comments.destroy');
        Route::post('/publicaciones/{post}/compartir', [PostEngagementController::class, 'share'])->name('posts.shares.store');
        Route::get('/promociones', [PostPromotionController::class, 'index'])->name('promotions.index');
        Route::post('/promociones', [PostPromotionController::class, 'store'])->name('promotions.store');
        Route::post('/promociones/{promotion}/pagar', [PostPromotionController::class, 'checkout'])->name('promotions.checkout');
        Route::get('/promociones/{promotion}/resultado', [PostPromotionController::class, 'returned'])->name('promotions.return');
        Route::get('/productos/{listing}/comprar', [ProductOrderController::class, 'checkout'])->name('products.checkout');
        Route::post('/productos/{listing}/pedidos', [ProductOrderController::class, 'store'])->name('products.orders.store');
        Route::post('/pedidos/{order}/simular-pago', [ProductOrderController::class, 'simulatePayment'])->name('products.orders.simulate-payment');
        Route::patch('/pedidos/{order}/listo', [ProductOrderController::class, 'ready'])->name('products.orders.ready');
        Route::patch('/pedidos/{order}/entregar', [ProductOrderController::class, 'deliver'])->name('products.orders.deliver');
        Route::patch('/pedidos/{order}/cancelar', [ProductOrderController::class, 'cancel'])->name('products.orders.cancel');
        Route::get('/notificaciones', [NotificationController::class, 'index'])->name('notifications.index');
        Route::patch('/notificaciones/leer-todas', [NotificationController::class, 'readAll'])->name('notifications.read-all');
        Route::patch('/notificaciones/{notification}/abrir', [NotificationController::class, 'open'])->name('notifications.open');
        Route::get('/mensajes', [ConversationController::class, 'index'])->name('conversations.index');
        Route::post('/mensajes/iniciar', [ConversationController::class, 'start'])->name('conversations.start');
        Route::post('/publicaciones/{post}/conversacion', [NegotiationConversationController::class, 'start'])->name('posts.conversations.start');
        Route::get('/mensajes/{conversation}/actualizaciones', [ConversationController::class, 'messages'])->middleware('throttle:120,1')->name('conversations.messages.index');
        Route::get('/mensajes/{conversation}', [ConversationController::class, 'show'])->name('conversations.show');
        Route::post('/mensajes/{conversation}', [ConversationController::class, 'store'])->name('conversations.messages.store');
        Route::patch('/mensajes/{conversation}/extender', [NegotiationConversationController::class, 'extend'])->name('conversations.extend');
        Route::patch('/mensajes/{conversation}/terminar', [NegotiationConversationController::class, 'close'])->name('conversations.close');
        Route::get('/solicitudes/{jobRequest}/propuestas', [JobProposalController::class, 'index'])->name('job-proposals.index');
        Route::post('/solicitudes/{jobRequest}/propuestas', [JobProposalController::class, 'store'])->name('job-proposals.store');
        Route::patch('/solicitudes/{jobRequest}/propuestas/{proposal}/aceptar', [JobProposalController::class, 'accept'])->name('job-proposals.accept');
        Route::patch('/solicitudes/{jobRequest}/propuestas/{proposal}/rechazar', [JobProposalController::class, 'reject'])->name('job-proposals.reject');
        Route::patch('/solicitudes/{jobRequest}/propuestas/{proposal}/retirar', [JobProposalController::class, 'withdraw'])->name('job-proposals.withdraw');
        Route::get('/trabajos', [ServiceOrderController::class, 'index'])->name('orders.index');
        Route::get('/trabajos/{order}', [ServiceOrderController::class, 'show'])->name('orders.show');
        Route::post('/trabajos/{order}/simular-pago', [ServiceOrderController::class, 'simulatePayment'])->name('orders.simulate-payment');
        Route::patch('/trabajos/{order}/iniciar', [ServiceOrderController::class, 'start'])->name('orders.start');
        Route::patch('/trabajos/{order}/entregar', [ServiceOrderController::class, 'deliver'])->name('orders.deliver');
        Route::patch('/trabajos/{order}/completar', [ServiceOrderController::class, 'complete'])->name('orders.complete');
        Route::patch('/trabajos/{order}/cancelar', [ServiceOrderController::class, 'cancel'])->name('orders.cancel');
        Route::post('/trabajos/{order}/disputas', [DisputeController::class, 'store'])->name('disputes.store');
        Route::get('/disputas/{dispute}', [DisputeController::class, 'show'])->name('disputes.show');
        Route::post('/disputas/{dispute}/respuestas', [DisputeController::class, 'reply'])->name('disputes.reply');
        Route::patch('/disputas/{dispute}/resolver', [DisputeController::class, 'resolve'])->name('disputes.resolve');
        Route::post('/trabajos/{order}/calificaciones', [ReviewController::class, 'store'])->name('reviews.store');
        Route::patch('/calificaciones/{review}', [ReviewController::class, 'update'])->name('reviews.update');
    });
});

Route::post('/email/verification-notification', [EmailVerificationNotificationController::class, 'store'])
    ->middleware(['auth', 'throttle:6,1'])
    ->name('verification.send');

Route::get('/administracion/login', [AdminSessionController::class, 'create'])->name('admin.login');
Route::get('/administracion/recuperar', [AdminPasswordController::class, 'request'])->name('admin.password.request');
Route::post('/administracion/recuperar', [AdminPasswordController::class, 'send'])->middleware('throttle:3,1')->name('admin.password.email');
Route::get('/administracion/restablecer/{token}', [AdminPasswordController::class, 'reset'])->name('admin.password.reset');
Route::post('/administracion/restablecer', [AdminPasswordController::class, 'update'])->middleware('throttle:6,1')->name('admin.password.update');
Route::post('/administracion/login', [AdminSessionController::class, 'store'])->middleware('throttle:10,1')->name('admin.login.store');
Route::get('/administracion/invitacion/{token}', [AdminTeamController::class, 'invitation'])->name('admin.invitation.show');
Route::post('/administracion/invitacion/{token}', [AdminTeamController::class, 'accept'])->middleware('throttle:10,1')->name('admin.invitation.accept');
Route::middleware(['auth:admin', 'auth.session'])->group(function () {
    Route::post('/administracion/logout', [AdminSessionController::class, 'destroy'])->name('admin.logout');
    Route::get('/administracion/verificar', [AdminSessionController::class, 'verification'])->name('admin.verification.notice');
    Route::post('/administracion/verificar/correo', [AdminSessionController::class, 'resend'])->middleware('throttle:3,1')->name('admin.verification.send');
    Route::get('/administracion/verificar/correo/{id}/{hash}', [AdminSessionController::class, 'verify'])->middleware('signed')->name('admin.verification.verify');
    Route::post('/administracion/verificar/telefono/enviar', [PhoneVerificationController::class, 'send'])->middleware('throttle:3,1')->name('admin.phone.send');
    Route::post('/administracion/verificar/telefono', [PhoneVerificationController::class, 'verify'])->middleware('throttle:6,1')->name('admin.phone.verify');
});
Route::middleware(['administrative.access', 'auth.session'])->group(function () {
    Route::get('/administracion/usuarios/{user}/perfil', [ProfileController::class, 'show'])->name('admin.users.preview');
    Route::get('/administracion/disputas', [DisputeController::class, 'adminIndex'])->name('disputes.admin-index');
    Route::get('/administracion/resumen', [AdminController::class, 'summary'])->middleware('throttle:120,1')->name('admin.summary');
    Route::get('/administracion', [AdminController::class, 'index'])->name('admin.index');
    Route::get('/administracion/soporte', [SupportController::class, 'adminIndex'])->name('admin.support.index');
    Route::get('/administracion/soporte/{ticket}', [SupportController::class, 'show'])->name('admin.support.show');
    Route::patch('/administracion/soporte/{ticket}/estado', [SupportController::class, 'updateStatus'])->name('admin.support.status');
    Route::get('/administracion/usuarios', [AdminDirectoryController::class, 'users'])->name('admin.users.index');
    Route::get('/administracion/usuarios/{user}', [AdminDirectoryController::class, 'showUser'])->name('admin.users.show');
    Route::patch('/administracion/usuarios/{user}/suspender', [AdminAccountController::class, 'suspend'])->name('admin.users.suspend');
    Route::patch('/administracion/usuarios/{user}/reactivar', [AdminAccountController::class, 'reactivate'])->name('admin.users.reactivate');
    Route::patch('/administracion/usuarios/{user}/baja', [AdminAccountController::class, 'deactivate'])->name('admin.users.deactivate');
    Route::get('/administracion/empleo', [AdminInsightsController::class, 'jobs'])->name('admin.jobs.index');
    Route::get('/administracion/operaciones', [AdminInsightsController::class, 'operations'])->name('admin.operations.index');
    Route::get('/administracion/publicidad', [AdminInsightsController::class, 'promotions'])->name('admin.promotions.index');
    Route::get('/administracion/pagos', [AdminInsightsController::class, 'payments'])->name('admin.payments.index');
    Route::get('/administracion/publicaciones', [AdminDirectoryController::class, 'posts'])->name('admin.posts.index');
    Route::patch('/administracion/publicaciones/{post}/retirar', [AdminController::class, 'removePost'])->name('admin.posts.remove');
    Route::get('/administracion/proveedores/{vendor}', [AdminDirectoryController::class, 'showVendor'])->name('admin.vendors.show');
    Route::get('/administracion/proveedores', [AdminDirectoryController::class, 'vendors'])->name('admin.vendors.index');
    Route::patch('/administracion/proveedores/{vendor}/aprobar', [AdminController::class, 'approveVendor'])->name('admin.vendors.approve');
    Route::patch('/administracion/proveedores/{vendor}/rechazar', [AdminController::class, 'rejectVendor'])->name('admin.vendors.reject');
    Route::patch('/administracion/proveedores/{vendor}/suspender', [AdminController::class, 'suspendVendor'])->name('admin.vendors.suspend');
    Route::patch('/administracion/proveedores/{vendor}/verificar', [AdminController::class, 'verifyVendor'])->name('admin.vendors.verify');
    Route::delete('/administracion/proveedores/{vendor}/verificacion', [AdminController::class, 'revokeVendorVerification'])->name('admin.vendors.verification.revoke');
    Route::patch('/administracion/documentos-verificacion/{document}', [VendorVerificationDocumentController::class, 'review'])->name('admin.verification-documents.review');
    Route::post('/administracion/comunidades', [AdminController::class, 'storeCommunity'])->name('admin.communities.store');
    Route::post('/administracion/codigos-postales/importar', [AdminController::class, 'importPostalCodes'])->name('admin.postal-codes.import');
    Route::patch('/administracion/comunidades/{community}', [AdminController::class, 'updateCommunity'])->name('admin.communities.update');
    Route::patch('/administracion/comunidades/{community}/estado', [AdminController::class, 'toggleCommunity'])->name('admin.communities.toggle');
    Route::delete('/administracion/comunidades/{community}', [AdminController::class, 'destroyCommunity'])->name('admin.communities.destroy');
    Route::post('/administracion/rubros', [AdminController::class, 'storeCategory'])->name('admin.categories.store');
    Route::patch('/administracion/rubros/{category}/estado', [AdminController::class, 'toggleCategory'])->name('admin.categories.toggle');
    Route::get('/administracion/equipo', [AdminTeamController::class, 'index'])->name('admin.team.index');
    Route::post('/administracion/equipo/invitar', [AdminTeamController::class, 'invite'])->name('admin.team.invite');
    Route::patch('/administracion/equipo/{admin}/acceso', [AdminTeamController::class, 'toggle'])->name('admin.team.toggle');
    Route::get('/administracion/mi-cuenta-plaza', [AdminTeamController::class, 'marketplace'])->name('admin.identity.show');
    Route::post('/administracion/mi-cuenta-plaza', [AdminTeamController::class, 'createMarketplace'])->name('admin.identity.create');
    Route::get('/administracion/soporte/{ticket}/mensajes', [SupportController::class, 'messages'])->name('admin.support.messages.index');
    Route::post('/administracion/soporte/{ticket}/respuestas', [SupportController::class, 'reply'])->name('admin.support.reply');
    Route::get('/administracion/notificaciones', [NotificationController::class, 'index'])->name('admin.notifications.index');
    Route::patch('/administracion/notificaciones/leer-todas', [NotificationController::class, 'readAll'])->name('admin.notifications.read-all');
    Route::patch('/administracion/notificaciones/{notification}/abrir', [NotificationController::class, 'open'])->name('admin.notifications.open');
    Route::get('/administracion/actividad/resumen', [NotificationController::class, 'summary'])->name('admin.activity.summary');
    Route::get('/administracion/disputas/{dispute}', [DisputeController::class, 'show'])->name('admin.disputes.show');
    Route::post('/administracion/disputas/{dispute}/respuestas', [DisputeController::class, 'reply'])->name('admin.disputes.reply');
    Route::patch('/administracion/disputas/{dispute}/resolver', [DisputeController::class, 'resolve'])->name('admin.disputes.resolve');
    Route::get('/administracion/documentos/{document}', [VendorVerificationDocumentController::class, 'download'])->name('admin.verification-documents.download');
});
Route::middleware(['auth:web', 'marketplace.identity'])->group(function () {
    Route::get('/verificar-telefono', [PhoneVerificationController::class, 'show'])->name('phone.show');
    Route::post('/verificar-telefono/enviar', [PhoneVerificationController::class, 'send'])->middleware('throttle:3,1')->name('phone.send');
    Route::post('/verificar-telefono', [PhoneVerificationController::class, 'verify'])->middleware('throttle:6,1')->name('phone.verify');
});
