<!DOCTYPE html>
<html lang="es">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Disputa - Plaza Local</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="min-h-screen bg-brand-surface text-brand-ink antialiased">
@php($reasonLabels = ['not_delivered' => 'No entregó', 'different_work' => 'Trabajo diferente', 'price_problem' => 'Problema con el precio', 'poor_service' => 'Mal servicio', 'no_show' => 'No se presentó', 'other' => 'Otro motivo'])
<header class="border-b border-brand/10 bg-white"><div class="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><a class="font-black" href="{{ route('dashboard') }}">Plaza Local</a><a class="rounded-full border border-brand/10 px-4 py-2 text-sm font-black" href="{{ route('orders.show', $dispute->order) }}">Ver trabajo</a></div></header>
<main class="mx-auto max-w-5xl px-5 py-9">
    @if(session('status'))<div class="mb-6 rounded-2xl bg-brand-success-soft px-5 py-4 text-sm font-black text-brand-success">{{ session('status') }}</div>@endif
    @if($errors->any())<div class="mb-6 rounded-2xl bg-red-50 px-5 py-4 text-sm font-black text-red-700">{{ $errors->first() }}</div>@endif
    <section class="rounded-[2rem] bg-brand p-6 text-white sm:p-8"><p class="text-xs font-black uppercase tracking-[.18em] text-brand-peach-muted">Expediente {{ substr($dispute->public_id, 0, 8) }}</p><div class="mt-3 flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-3xl font-black">{{ $reasonLabels[$dispute->reason] ?? 'Incidencia' }}</h1><p class="mt-3 text-white/65">{{ $dispute->order->jobRequest?->title }} · Abierta por {{ $dispute->opener->name }}</p></div><span class="rounded-full bg-white/10 px-4 py-2 text-sm font-black">{{ $dispute->status->value === 'open' ? 'En revisión' : 'Resuelta' }}</span></div></section>
    <div class="mt-6 grid gap-6 lg:grid-cols-[1fr_330px]">
        <section class="rounded-[1.75rem] border border-brand/10 bg-white p-6 shadow-sm"><h2 class="text-xl font-black">Conversación del expediente</h2><div class="mt-5 space-y-4">@foreach($dispute->messages as $message)<article class="rounded-2xl bg-brand-surface p-4"><div class="flex justify-between gap-3"><strong>{{ $message->user->name }}</strong><span class="text-xs font-bold text-brand-caption">{{ $message->created_at->diffForHumans() }}</span></div><p class="mt-2 whitespace-pre-line leading-7 text-brand-copy">{{ $message->body }}</p></article>@endforeach</div>
            @if($dispute->status->value === 'open')<form class="mt-5" method="POST" action="{{ route('disputes.reply', $dispute) }}">@csrf<textarea class="min-h-28 w-full rounded-2xl border border-brand/10 bg-brand-surface px-4 py-3" name="body" maxlength="2000" required placeholder="Agrega información relevante"></textarea><button class="mt-3 rounded-full bg-brand px-5 py-3 text-sm font-black text-white" type="submit">Agregar respuesta</button></form>@endif
        </section>
        <aside class="space-y-4"><section class="rounded-[1.75rem] border border-brand/10 bg-white p-5"><h2 class="font-black">Descripción inicial</h2><p class="mt-3 whitespace-pre-line text-sm leading-6 text-brand-copy">{{ $dispute->description }}</p></section>
            @if($dispute->status->value === 'resolved')<section class="rounded-[1.75rem] bg-brand-success-soft p-5"><h2 class="font-black text-brand-success">Resolución</h2><p class="mt-3 text-sm leading-6">{{ $dispute->resolution }}</p><p class="mt-3 text-xs font-bold text-brand-muted">Por {{ $dispute->resolver?->name }}</p></section>@endif
            @if($isAdmin && $dispute->status->value === 'open')<section class="rounded-[1.75rem] bg-brand-orange-soft p-5"><h2 class="font-black">Resolver como administrador</h2><form class="mt-4 space-y-3" method="POST" action="{{ route('disputes.resolve', $dispute) }}">@csrf @method('PATCH')<select class="w-full rounded-2xl border border-brand-orange/20 bg-white px-4 py-3" name="outcome" required><option value="resume">Reanudar estado anterior</option><option value="complete">Marcar completado</option><option value="cancel">Cancelar contratación</option></select><textarea class="min-h-28 w-full rounded-2xl border border-brand-orange/20 bg-white px-4 py-3" name="resolution" minlength="20" maxlength="3000" required placeholder="Fundamento de la decisión"></textarea><button class="w-full rounded-full bg-brand-orange px-5 py-3 font-black text-white" type="submit">Guardar resolución</button></form></section>@endif
        </aside>
    </div>
</main>
</body></html>
